### ISSUE TITLE
F-Droid Support?

### ISSUE THREAD

**Issue by pjalsGit** [EFForg/apkeep#5] opened 2021-09-03 08:53 UTC

**Comment by Hainish** [comment] 2021-09-03 17:48
We definitely should support F-Droid.  Looks like it has some good API documentation: https://f-droid.org/en/2021/02/05/apis-for-all-the-things.html

**Comment by pjalsGit** [comment] 2021-09-03 19:31
oh and i made a rival to apkeep so yeah lool

**Comment by eighthave** [comment] 2021-09-08 06:52
@Hainish we're also happy to help you get going with the APIs.  You can find us here https://f-droid.org/en/about/#contact

**Comment by pjalsGit** [comment] 2021-09-08 07:44
the api just goes like this: 
get `https://gitlab.com/fdroid/fdroiddata/-/raw/master/metadata/ID_HERE.yml`
parse with yaml parser
get CurrentVersionCode
get `http://f-droid.org/repo/ID_HERE.VERSION_CODE_HERE`

**Comment by eighthave** [comment] 2021-09-08 07:52
That will work for apps that explicitly declare `CurrentVersionCode`, but not 
for most, where it is implicitly declared.

The app index is the canonical source, but isn't really an API.  Its an index of 
all available apps and APKs.  Basically, do

* `wget https://f-droid.org/repo/index-v1.jar`
* verify JAR signature
* extract `index-v1.json`

You can see that in action here:
https://gitlab.com/fdroid/fdroidserver/-/blob/2.0.1/fdroidserver/index.py#L696

**Comment by Hainish** [comment] 2021-09-22 21:33
I've added support for F-Droid in c30cda59d620ea58d747a310870154d13b0533b9.  If all goes well and everything cross-compiles gracefully, I'll close this issue.

**Comment by Hainish** [comment] 2021-09-23 00:20
Confirmed cross-compiling works, closing

**Closed by Hainish** 2021-09-23 00:20 UTC
Labels: enhancement, f-droid
